test:
  name: Benchmarking of test network environment
  description: >-
    experimenting with the benchmarking settings
  workers:
    number: 2
  rounds:
    - label: readAsset-fixed-rate (100)
      description: Read asset with fixed rate benchmark
      txDuration: 60
      rateControl:
        type: fixed-rate
        opts:
          tps: 100
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
    - label: readAsset-fixed-rate (1000)
      description: Read asset with fixed rate benchmark
      txDuration: 60
      rateControl:
        type: fixed-rate
        opts:
          tps: 1000
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
    - label: readAsset-fixed-rate (10000)
      description: Read asset with fixed rate benchmark
      txDuration: 60
      rateControl:
        type: fixed-rate
        opts:
          tps: 10000
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
    - label: readAsset-fixed-load (100)
      description: Read asset with fixed load benchmark
      txDuration: 60
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 100
          startingTps: 100
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
    - label: readAsset-fixed-load (1000)
      description: Read asset with fixed load benchmark
      txDuration: 60
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 1000
          startingTps: 100
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
    - label: readAsset-fixed-load (10000)
      description: Read asset with fixed load benchmark
      txDuration: 60
      rateControl:
        type: fixed-load
        opts:
          transactionLoad: 10000
          startingTps: 100
      workload:
        module: workload/readAsset.js
        arguments:
          assets: 10
          contractID: IoT-cc
monitors:
  # transaction:
  #   - module: logging
  resource:
    - module: docker
      options:
        interval: 5
        containers:
          - /peer0.org1.example.com
          - /peer0.org2.example.com
          - /peer0.org3.example.com
          - /orderer.example.com
        charting:
          bar:
            metrics: [Memory(max), CPU%(max)]
          polar:
            metrics: [Memory(max), CPU%(max)]
